name: Linter and Tester
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pylint
        run: pip install pylint
      - name: Run linter on haromszog.py
        run: python3 linter.py
        continue-on-error: false
      - name: Checkout
        uses: actions/checkout@v3
        - name: Install pytest
        run: pip install pytest
      - name: Run tests on haromszog.py
        run: python3 test.py
       continue-on-error: false